#TICKETS

# get a list of tickets using an user id parameter
GET http://localhost:8080/users/1/tickets?page-size=1&page-num=1

###
# get a list of tickets using an event id parameter
GET http://localhost:8080/events/1/tickets?page-size=5&page-num=1

###
# book ticket
POST http://localhost:8080/api/tickets
Content-Type: application/json

{
  "id": 26,
  "eventId": 1,
  "userId": 1,
  "category": "BAR",
  "place": null
}
###
# delete a ticket using an id parameter
DELETE http://localhost:8080/api/tickets/26

###
# pdf
GET http://localhost:8080/api/tickets/pdf?userId=1&page-size=10&page-num=1
Content-Type: application/pdf

###
# preload tickets
POST http://localhost:8080/api/tickets/preload

###


#USERS
# get user by id
GET http://localhost:8080/api/users/55

###
# get user by email
GET http://localhost:8080/api/users/email/email@1

###
# create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "id": 55,
  "name": "J",
  "email": "J@g.c"
}

###
# update user
PUT http://localhost:8080/api/users/55
Content-Type: application/json

{
  "id": 55,
  "name": "Oleh",
  "email": "oleh12@gmail.com"
}

###
# delete user
DELETE http://localhost:8080/api/users/55

###





#EVENTS
# get all events
GET http://localhost:8080/events

###
# get event by event id
GET http://localhost:8080/api/events/2

###
# get a list of events by title
GET http://localhost:8080/api/events/title/1%20Concert?page-size=1&page-num=1

###
# get a list of events by date
GET http://localhost:8080/api/events/date/2022-01-01?page-size=1&page-num=1

###
# create event
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "eventId": 28,
  "title": "1 Concert",
  "date": "2022-01-01"
}

###
# update event
PUT http://localhost:8080/api/events/26
Content-Type: application/json

{
  "eventId": 26,
  "title": "1 Concert",
  "date": "2022-01-18"
}

###
# update event name
PATCH http://localhost:8080/api/events/26
Content-Type: application/json

"Concert 18"

###
# delete an event using an id parameter
DELETE http://localhost:8080/api/events/26

###




